---
gitRepo: "ArcBlock/forge-docs"
srcPath: "src"
categories:
  docs:
    basePath: "/docs"
    title: "Docs"
    link: "/intro"
    priority: 9999
    sidebar:
      Introduction:
        links:
          - "/intro/quickstart"
          - "/intro/concepts"
        locales:
          zh: "Forge 入门"
      Usage:
        links:
          - "/instruction/install"
          - "/instruction/configuration"
        locales:
          zh: "基本方法"
      Reference:
        links:
          - "/reference/rpc"
          - "/reference/txs"
          - "/reference/code"
          - "/reference/types"
        locales:
          zh: "Forge 原理"
      Forge SDK:
        links:
          - "/instruction/sdk"
          - "/instruction/sdk/js"
          - "/instruction/sdk/java"
          - "/instruction/sdk/python"
          - "/instruction/sdk/elixir"
        locales:
          zh: "Forge SDK"
      Forge Tools:
        links:
          - "/tools"
          - "/tools/forge_web"
          - "/tools/abt_chain_node"
          - "/tools/dapps_workshop"
          - "/tools/simulator"
          - "/tools/forge_indexer"
        locales:
          zh: "工具箱"
