---
gitRepo: "ArcBlock/forge-docs"
srcPath: "src"
categories:
  docs:
    basePath: "/docs"
    title: "Docs"
    link: "/"
    priority: 9999
    sidebar:
      'null':
      - "/"
      Quick Start:
      - "/blocklets/intro"
      - "/blocklets/official"
      - "/blocklets/community"
      Step-By-Step Guides:
      - "/concepts/inside_forge"
      - "/concepts/transaction"
      - "/concepts/account"
      - "/concepts/tx_protocol"
      Usage:
      - "/instruction/install"
      - "/instruction/configuration"
      - "/instruction/log"
      Reference:
      - "/instruction/sdk"
      - "/reference/code"
      - "/reference/protocols"
      - "/reference/txs"
      - "/reference/rpc"
      - "/reference/types"
      Forge Tools:
      - "/tools"
      - "/tools/forge_cli"
      - "/tools/forge_web"
      - "/tools/abt_chain_node"
      - "/tools/simulator"
      - "/tools/forge_indexer"
      - "/tools/dapps_workshop"
