---
gitRepo: "ArcBlock/forge-docs"
srcPath: "src"
categories:
  docs:
    basePath: "/docs"
    title: "Docs"
    link: "/"
    priority: 9999
    sidebar:
      'null':
      - "/"
      Quick Start:
      - "/blocklets/intro"
      - "/blocklets/official"
      - "/blocklets/community"
      Step-By-Step Guides:
      - "/concepts/inside_forge"
      - "/concepts/transaction"
      - "/concepts/account"
      - "/concepts/tx_protocol"
      Usage:
      - "/instruction/install"
      - "/instruction/configuration"
      - "/instruction/log"
      Library:
      - "/instruction/sdk"
      - "/reference/code"
      - "/reference/protocols"
      - "/reference/txs"
      - "/reference/rpc"
      - "/reference/types"
      Forge Tools:
      - "/tools"
      - "/tools/forge_cli"
      - "/tools/forge_web"
      - "/tools/abt_chain_node"
      - "/tools/simulator"
      - "/tools/forge_indexer"
      - "/tools/dapps_workshop"
  tutorials:
    basepath: "/docs"
    title: "Tutorials"
    link: "/tutorials"
    priority: 8888
    sidebar:
      'null':
      - "/"
  blogs:
    basepath: "/dummy"
    title: "Blogs"
    link: "/blogs"
    priority: 7777
  showcase:
    basepath: "/showcase"
    title: "Showcase"
    link: "/"
    priority: 6666
  community:
    basepath: "/community"
    title: "Community"
    link: "/"
    priority: 5555
