name: Npm deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Deploy:

    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Deploy
      env:
        AWS_NODE_ENDPOINT: ${{ secrets.AWS_NODE_ENDPOINT }}
        AWS_NODE_ACCESS_KEY: ${{ secrets.AWS_NODE_ACCESS_KEY }}
        AWS_NODE_ACCESS_SECRET: ${{ secrets.AWS_NODE_ACCESS_SECRET }}
        ALIYUN_NODE_ENDPOINT: ${{ secrets.ALIYUN_NODE_ENDPOINT }}
        ALIYUN_NODE_ACCESS_SECRET: ${{ secrets.ALIYUN_NODE_ACCESS_SECRET }}
        ALIYUN_NODE_ACCESS_KEY: ${{ secrets.ALIYUN_NODE_ACCESS_KEY }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
        GATSBY_ALGOLIA_ADMIN_KEY: ${{ secrets.GATSBY_ALGOLIA_ADMIN_KEY }}
        GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
        GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}

      run: bash ./tools/publish.sh
